### ISSUE TITLE
When Local-SSL is active client is not able to add new websites to my MainWP dashboard

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/local-ssl#10]
I have enabled the SSL plugin and added the ServerPress certificate to my Firefox browser.

I my local WordPress site I installed the plugin MainWP (WordPress dashboard manager) and I noticed the following issue:

- when i enable the option Local SSL Settings/Enable Upgrade All Connections to HTTPS in WordPress then I am not able to add new websites to my MainWP dashboard. When I disable this option I can add new websites to MainWP.

After adding the websites to MainWP I can enable this option again, and the syncing process between MainWP and my Child websites is working just fine.

So this problem only exist when I try to add a new website to MainWP. After the website is added I can enable Local SSL option without any problem.

HS Ticket # https://secure.helpscout.net/conversation/934023872/208356/

**Comment by shadowdao** [comment]
This is ultimately an issue with MainWP with how it validates the SSL on add.  Nothing can be done on our side.
