### ISSUE TITLE
Local SSL Setting Contains Typo

### ISSUE THREAD

**Issue by MarcBenzakein** [ServerPress/local-ssl#13]
#### STEPS TO REPRODUCE: 
1. Go to Local SSL in Settings (WordPress Dashboard)
2. Top of screen says, "Activating this option will forces" instead of "Activating this option will force"

#### RESULT: 
[Description] 
It hurts my eyes.

#### EXPECTED RESULT: 
[Description] 
No eye pain

**Comment by shadowdao** [comment]
Fixed with the Benzakein update
