### ISSUE TITLE
MainWP does not recognize https://

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/local-ssl#4]
HelpScout Ticket: https://secure.helpscout.net/conversation/586969907/200528?folderId=88236

I am using the plugin MainWP for my sites. If I change my sites to SSL MainWP does not recognize them. They have to be http only sites. I am not sure if you can do anything about this but thought you might like to know.

OS: Windows 10

**Comment by shadowdao** [comment]
Looks like MainWP is trying to validate the SSL, which will fail as they are still self signed SSLs.  Turning off 'Verify certificate' allows it to work correctly again.

**Comment by GreggFranklin** [comment]
![sites_ _test_ _wordpress](https://user-images.githubusercontent.com/1041421/40461885-3f7434ee-5ec2-11e8-8300-8ba75980d3da.png)

The resolution has been added into the knowledge base.
