### ISSUE TITLE
Receiving this error after changes made

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/local-ssl#5]
Producing the following errors. 

![screen shot 2018-06-10 at 2 20 56 pm](https://user-images.githubusercontent.com/1041421/41206502-e21e43e2-6cb9-11e8-84b2-b0fa8bccda1e.jpg)

** Josh has a resolution and the detect code for placement of the plugin. 

**We would like to revert back to the previous commit. Josh will submit commits.

**Comment by davejesch** [comment]
fixed https://github.com/ServerPress/local-ssl/commit/40c600ee90c0b0d4cc51cb1481ba829d33852dbd

**Comment by GreggFranklin** [comment]
**Object not found!**
The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the webmaster.

Error 404
test60.dev.cc
Apache/2.4.29 (Unix) OpenSSL/1.0.2n PHP/7.1.13 mod_perl/2.0.8-dev Perl/v5.16.3

Noted: The SSL Certificate was not created in the ssl-cert folder do to code change. 
--- Josh is looking into this.
