### ISSUE TITLE
The changes have caused the creation of sites to fail. 

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/local-ssl#7]
![image 15](https://user-images.githubusercontent.com/1041421/43469952-3bbff06c-949c-11e8-8271-ddb68802e14d.jpg)

**Comment by GreggFranklin** [comment]
This was using the branch. Nothing in the Apache error.log

**Comment by davejesch** [comment]
By the way, also note that the URL in your picture is using http, not https. You'll need to change that when loading the page.

**Comment by GreggFranklin** [comment]
I downloaded the latest branch, uncompressed and copied to ds-plugins
Started Trace
Created a site, it did not forward to https:// but generated the same error as above. 
I then went to https:// and received the following error
![image 19](https://user-images.githubusercontent.com/1041421/43492993-8c8da00e-94e0-11e8-89bd-4ff2d4cf61a8.jpg)

Here is what Trace output:
16:36:58.00 (string) dbarchive: inside DS_Database_Archive::check_perform_archive()
16:36:58.01 (string) dbarchive: runtime: DS_Runtime::__set_state(array(
   'preferences' => 
  stdClass::__set_state(array(
     'version' => '3.9.1',
     'edition' => 'Premium',
     'webOwner' => '',
     'dbUser' => 'root',
     'dbPass' => '',
     'browser' => 'Safari',
     'tld' => '.dev.cc',
     'ds-plugins' => 
    stdClass::__set_state(array(
       'Admin Color Bar' => 'c:\\xampplite\\ds-plugins\\admin-color-bar\\admin-color-bar.php',
       'Airplane Mode' => 'c:\\xampplite\\ds-plugins\\airplane-mode\\airplane-mode.php',
       'Bypass Login' => 'c:\\xampplite\\ds-plugins\\bypass-login\\bypass-login.php',
       'Clean Import' => 'c:\\xampplite\\ds-plugins\\clean-import\\clean-import.php',
       'Database Archive' => 'c:\\xampplite\\ds-plugins\\database-archive\\database-archive.php',
       'Database Collation Fix' => 'c:\\xampplite\\ds-plugins\\databasecollationfix\\databasecollationfix.php',
       'Debug and Trace' => 'c:\\xampplite\\ds-plugins\\debug-trace\\debug-trace.php',
       'Dreamweaver Support' => 'c:\\xampplite\\ds-plugins\\dreamweaver-support\\dw-support.php',
       'DS-CLI' => 'c:\\xampplite\\ds-plugins\\ds-cli\\ds-cli.php',
       'InnoDB Aut
16:36:58.04 (string) dbarchive: ds dir=c:\xampplite\
16:36:58.07 (string) dbarchive: file=c:\xampplite\tmp/dbarchive.dat
16:36:58.25 (string) localssl: inside local_ssl_https_verify()
16:37:02.00 (string) localssl: local_ssl_create_ssl() exec: C:\xampplite\ds-plugins\local-ssl\win32\cygwin\bin\openssl.exe req -new -newkey rsa:2048 -sha256 -nodes -keyout "C:\xampplite\ds-plugins\local-ssl\test3.dev.cc.key" -subj "/C=US/ST=California/L=Los Angeles/O=DesktopServer/CN=*.test3.dev.cc" -out "C:\xampplite\ds-plugins\local-ssl\test3.dev.cc.csr" 2>&1
16:37:03.00 (string) localssl: local_ssl_create_ssl() exec: C:\xampplite\ds-plugins\local-ssl\win32\cygwin\bin\openssl.exe x509 -req -in "C:\xampplite\ds-plugins\local-ssl\test3.dev.cc.csr" -CA "C:\xampplite\ds-plugins\local-ssl\ServerPressCA.crt" -CAkey "C:\xampplite\ds-plugins\local-ssl\ServerPressCA.key" -CAcreateserial -out "C:\xampplite\ds-plugins\local-ssl\test3.dev.cc.crt" -days 3650 -sha256 -extfile "C:\xampplite\ds-plugins\local-ssl\_test3.dev.cc_v3.ext" 2>&1

**Comment by davejesch** [comment]
Does this file exist: C:\xampplite\ds-plugins\local-ssl\ServerPressCA.crt
There might be a problem with the local_ssl_create_root_ca() function not creating the file.

**Comment by GreggFranklin** [comment]
Yes that file does exist.

**Comment by GreggFranklin** [comment]
Issue is resolved.
