### ISSUE TITLE
mac_root_ca_install.scpt exists in repo

### ISSUE THREAD

**Issue by davejesch** [ServerPress/local-ssl#8]
#### STEPS TO REPRODUCE: 
1. clone repository

#### RESULT: 
File mac_root_ca_install.scpt exists in repo

#### EXPECTED RESULT: 
There code in prepend_0.php to create this file which is OS dependent. If it's creating the file should the file be added to .gitignore and removed from the repo?

**Comment by shadowdao** [comment]
Nothing Creates that file in prepend, but it is called in the file to install the root ca on mac.  It should not be put in the .gitignore.

`shell_exec("osascript " . LOCAL_SSL_PATH . "mac_root_ca_install.scpt");`

This calls the OS X scripting language to run commands that we can't run directly from PHP.
