### ISSUE TITLE
Oxygen Theme and Local-SSL not playing nice. 

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/local-ssl#9]
Please review the video's from the link below. 

HelpScout: https://secure.helpscout.net/conversation/673992583/203411?folderId=88236
Link to videos: https://www.dropbox.com/s/6mixaxcvqa73zgc/DesktopServer%20Videos.rar?dl=0

**Comment by shadowdao** [comment]
Can't see the help scout link (dont have an account).  Can we get a copy of the plugin to test and see what the cause is? I suspect that it generates a static file at some point and doesn't update for URL changes.

**Comment by GreggFranklin** [comment]
The resolution is to go into the Dashboard > Settings > General and change the WordPress Address (URL) and Site Address (URL) to https://
